#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running Git Hooks'

# echo "🔎  Checking validity of types with TypeScript"

# yarn type-check || (
#     "⛔️  There is a type error in the code, fix it, and try commit again. ⛔️";
#     false;
#     )

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'


# echo "✅  No TypeError found"
echo "🔎  Running linter.."

npm run lint:fix || (
    echo '⛔️  There is a problem in the code. Check linter, add changes and try commit again. ⛔️';
    false;
    )

echo '✅ No Eslint error found'
echo '⌛️ Running lint staged and git commit ⌛️'

npx lint-staged